defaults:
  - grid_sets: default
  - params: default
  - plotting: default
  - slurm: default
  - _self_

# hydra:
#   job:
#     chdir: True
#   sweeper:
#     params:
#       ++params.EI_RNN_params.g: 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65
#       ++params.EI_RNN_params.ketamine_scale: 0.9, 0.95, 0.99, 0.999, 0.9999, 1, 1.0001, 1.001, 1.01, 1.05, 1.1
#       ++params.EI_RNN_params.ketamine_dose: 'low', 'high'
#       ++params.random_state: 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52
